# Generated by Django 4.2.6 on 2023-11-26 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dulces',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='saladas',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='veganas',
            name='comentario',
        ),
        migrations.AddField(
            model_name='curso',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todas',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
