# Generated by Django 4.2.6 on 2023-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Dulces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('calorias_por_porcion', models.TextField()),
                ('tiempo_de_coccion', models.TextField()),
                ('ingredientes', models.TextField()),
                ('pasos', models.TextField()),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Saladas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tiempo_de_coccion', models.TextField(blank=True, null=True)),
                ('ingredientes', models.TextField()),
                ('pasos', models.TextField()),
                ('tips', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veganas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('tiempo_de_coccion', models.TextField(null=True)),
                ('ingredientes', models.CharField(max_length=256)),
                ('ingredientes_alternativos', models.TextField(blank=True, null=True)),
                ('pasos', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
