# Generated by Django 4.2 on 2023-11-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_remove_dulces_comentario_remove_saladas_comentarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('autor', models.CharField(max_length=64)),
                ('imagenLibro', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
