# Generated by Django 4.2 on 2023-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('autor', models.CharField(max_length=64)),
                ('articulo', models.CharField(max_length=400)),
                ('imagenLibro', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
